name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: start Actions
      run: echo "Ansible-freeipa IDM_CI"
    - name: Start Docker Slave
      run: sudo docker start $(sudo docker ps -a -q | head -n 1)
    - name: Exec Docker Slave
      run: sudo docker exec $(sudo docker ps -a -q | head -n 1) /bin/bash -c "sh test_setup.sh"
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
        SOURCE_DIR: './'      # optional: defaults to entire repository
